version: '3'
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  auth:
    build:
      dockerfile: Dockerfile
      context: ./open-conquest-auth
    depends_on:
      - "mongo"
    environment:
      - SECRET=secret
      - PORT=5000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    ports:
    - "5000:5000"
